### ISSUE TITLE
ERROR IN LINE 213

### ISSUE THREAD

**Issue by ALEJANDRA-TOMASINI** [JamesDMSpeed/Mexican-mammal-phylogenetic-diversity#1]
Hello James, 
I keep having an error in line 213 of my script:

> communitydata<- getValues(mexicomammalstack_10km)

Error in file(fn, "rb") : cannot open the connection
In addition: Warning message:
In file(fn, "rb") :
  cannot open file '/tmp/RtmpwAHqgo/raster/r_tmp_2020-02-17_145320_1680_12073.gri': No such file or directory

I don't know what does this mean but I think it has to do with the ".gri" end of the file/directory it is searching cause I believe it should be ".grd" as that the end the mexicomammalstack_10km object has. I only have that problem with this object and is actually the same error I had when trying to re-project, then we decided to re-project until the end but when i tried to keep going, this same error happened again 

I'm not at the museum today so hopefully we can solve it through here. Thanks for the help !!

Alejandra

**Comment by JamesDMSpeed** [comment]
The issue seems to be finding the temp file where the 10km raster is stored (probably too large). You may be able to get around this by writing the mexicomammal10km stack to a file so it is not held in temporay memory.
I.e.
writeRaster(mexicomammalstack_10km,'somepathway/mexicomammalstack_10km',bylayer=T)
Then read it in from the file.
mexicomammalstack_10km<-stack('somepathway/mexicomammalstack_10km')

**Comment by ALEJANDRA-TOMASINI** [comment]
I tried now with:


> writeRaster(mexicomammalstack_10km,'~/Mexican-mammal-phylogenetic-diversity/mexicomammalstack_10km',bylayer=T)

Error in file(fn, "rb") : cannot open the connection
In addition: Warning messages:
1: In if (is.list(value)) value <- .resolveClassList(value, where,  :
  closing unused connection 3 (/home/shomeb/m/mariagui/Mexican-mammal-phylogenetic-diversity/mexicomammalstack_10km_1.gri)
2: In file(fn, "rb") :
  cannot open file '/tmp/RtmpwAHqgo/raster/r_tmp_2020-02-17_145320_1680_12073.gri': No such file or directory


then tried:

> writeRaster(mexicomammalstack_10km,'/home/shomeb/m/mariagui/Mexican-mammal-phylogenetic-diversity/mexicomammalstack_10km',bylayer=T)

Error in file(fn, "rb") : cannot open the connection
In addition: Warning message:
In file(fn, "rb") :
  cannot open file '/tmp/RtmpwAHqgo/raster/r_tmp_2020-02-17_145320_1680_12073.gri': No such file or directory

so got the same error as before 


<img width="844" alt="Screenshot 2020-02-18 at 10 14 20" src="https://user-images.githubusercontent.com/47723282/74721292-6fc3c000-5237-11ea-8bf2-019308b83db1.png">

I still believe there's a problem with the .gri termination cause when I open mexicomammalstack_10km it says its store in '/tmp/RtmpwAHqgo/raster/r_tmp_2020-02-17_145320_1680_12073.**grd**'


Also I was wondering if it was possible to just do it with mexmam_sr10km_m, but Im not sure cause i couldn't see the names of the species here, it just says "layer" in mexmam_sr10km_m where the names are listed in mexicomammalstack_10km.

**Comment by JamesDMSpeed** [comment]
You will need to recreate (aggregate) the 10km stack since it is lost in memory before writing it.
.grd and .gri files go together as the native file format on raster. You can always save as a geotif if you think the file type is the issue.

**Comment by ALEJANDRA-TOMASINI** [comment]
by recreate/aggregate you mean re-run it? like build it again?

**Comment by JamesDMSpeed** [comment]
Yes, run the lines to make the 10k layer, then save it to file

**Comment by ALEJANDRA-TOMASINI** [comment]
IT WORKED!
