### ISSUE TITLE
boxplots

### ISSUE THREAD

**Issue by ALEJANDRA-TOMASINI** [JamesDMSpeed/Mexican-mammal-phylogenetic-diversity#2]
So as I understood, you suggested to do a boxplot of the PD that is inside and outside protected areas and same for SR. 

For this I first used:

#SR in PA
SRiPA<-mask(SR_lcc,ALLPA_ToUse)
levelplot(SRiPA)
levelplot(SRiPA,par.settings=YlOrRdTheme,margin=F, main='Species Richness in Protected Areas',scales=list(draw=F))+
  layer(sp.polygons(mexicoEA1,lwd=0.5))+
  layer(sp.polygons(ALLPA_ToUse,lwd=0.5))

#BOXPLOT OF SRiPA 
boxplot(SRiPA, y=NULL, maxpixels=100000, col='blue', xlab='InsidePA', ylab='SR')

#PD in PA
PDiPA<-mask(PD_lcc,ALLPA_ToUse)
levelplot(PDiPA)
levelplot(PDiPA,par.settings=YlOrRdTheme, margin=F,main='Phylogenetic Diversity in Protected Areas')+
  layer(sp.polygons(ALLPA_ToUse,lwd=0.5))+
  layer(sp.polygons(mexicoEA1,lwd=0.5))

#BOXPLOT OF PDiPA 
boxplot(PDiPA, y=NULL, maxpixels=100000, col='RED', xlab='InsidePA', ylab='PD')

So I got the boxplot of the diversity inside the PA, however Im not sure how to calculate it outside.... I'm thinking managing to get the "difference" between the PA shape file and the on from Mexico, get a new shape file of this difference and then mas the PD/SP to this new shape file but I have no idea how to do it or how to google it so I've been thinking about that today...
What do you suggest?

**Comment by JamesDMSpeed** [comment]
One solution is to select only the cells outside the PAs. You can do that by running the mask function, but setting inverse=T

**Comment by JamesDMSpeed** [comment]
Another solution would be to rasterize the protected areas polygons (giving 1|0 data for inside|outside PAs), then extract the raster values for PA, SR and PD and use that dataframe to make the boxplots.

Also see ?bwplot in rasterVis for a violin:boxplot combination that is more information rich.

**Comment by ALEJANDRA-TOMASINI** [comment]
I managed now with the inverse function, thanks!
 violin:boxplot is for ggplot I think. In raster vis I just found violin.ratio may is this one?
