### ISSUE TITLE
working on biodiversity 

### ISSUE THREAD

**Issue by ALEJANDRA-TOMASINI** [JamesDMSpeed/Mexican-mammal-phylogenetic-diversity#4]
Hello James

I've been working yesterday on the beta diversity analysis.
the lines for these are from 409-448

So what I did was first extract one row that contained values 0f 0 and 1 for each of the species within the protected areas (whatever that have a value on the on the PA column), and deleted the last column that was the PA column, like this i built one single community for all the PA.
 
Then I kinda did the opposite, so I kept all of the rows that had values of 0 on the PA column, deleted the PA column and got the data set for individual non-protected cells

Then I bind these 2 data sets but got an error that I had some rows with only values of zero so I tried to delete rows with only zeros from the non-protected cells data set but I still had the same error.

Anyways, I obtained a matrix that looked like made sense to me: it had the values for every cell and at the end, a column and a row for the values off all cells compared to the PA community. 

The problem is that I'm not sure how to rasterise it. I was thinking doing this as I did the raster of the PD:

#Rasterize this
phydivraster<-raster(mexmam_sr10km_m)
phydivraster<-setValues(phydivraster,phydiv$PD)
phydivraster<-mask(phydivraster,mexmam_sr10km_m,maskvalue=NA)

so set the values of an existing raster to the info of my beta diversity, but then I realised that since I merged all the PA cells into one community, I have only one "cell" for all the PAs instead of x number of cells that compose the PAs network so then I think I can't rasterise it this way since I lost cells by doing this, so do you have a way to rasterise it even though I have way less cells?

On the other hand, I asked for help and got suggested another solution but tbh I don't fully understand this so Im not sure I can actually use it: 

I do everything as I did before for the PA community. For the unprotected-cell community, I mask the mammal stack with the PA and use that as a dataset so I keep the original number of cells, so I think in this case the cells for PAs will have zeros, but the the B diversity will be assed also for each cell of the PA,right? is this ok or possible? or does it even make sense?:

>communitydata_non_PA<-mask(mexicomammalstack_10km, ALLPA3, inverse='T')
>combined_communitydataPA <- rbind(getValues(communitydata_non_PA), communitydataPA)

>non_communitydataPA<-data.frame(PAnMmlStack[PAnMmlStack$PA_MX_Raster != 1])
>non_communitydataPA$PA_MX_Raster <- NULL  # remove PA_MX_Raster column
#non_communitydataPA<-non_communitydataPA[rowSums(non_communitydataPA[, -1] > 0) != 0, ] # removing rows with only zeros

>combined_communitydataPA <- rbind(non_communitydataPA, communitydataPA)

by doing this I get a super huge matrix and takes super long to build it and I still haven't rasterised it because Im just not sure this is ok 

I would like to do it the first way cause it seems closer to what you and i takes yesterday and i find it better to understand, but then agin i that way I dont know how would I rasterise that 

Could you suggest me something?

**Comment by JamesDMSpeed** [comment]
Hi Alejandra - I am not able to follow through your script on the repository but I get the general idea.

Yes-  I would also take the approach of masking the protected areas, and setting the values of the non-NA cells. 

When you get the large matrix, you need to select only elements that represent the turnover between the protected area cell and the others. 

Make sure you check carefully that the correct values are assigned to the correct cells.

**Comment by ALEJANDRA-TOMASINI** [comment]
The name of the script is Mexican Mammals.R las commit is from yesterday
I'm not sure it works this way. I've trying to do he beta diversity all day but R keeps crashing and I loose everything on my environment....
Now what I'm trying is to first crop to the Mexican borders so I don't have to compute the rest of the so distributions when doing the beta diversity

**Comment by ALEJANDRA-TOMASINI** [comment]
Hello James

Im having some issues with calculating the phylogenetic beta diversity (452-457). I'm not sure the data set that I built is appropriate because I keep getting an error that the producto that I get in line 457 is too big and cannot be saved.
I matched the community data that I made for the beta diversity and then matched it with the phylogeny so I had the info on PA, community data and phylogeny.

Could you give me some feedback on this please?

**Comment by JamesDMSpeed** [comment]
Is the community data every cell? Or have you combined the protected areas into a single 'community'?

**Comment by JamesDMSpeed** [comment]
It may be that you have to aggregate the other cells into a larger cell size in order to reduce the size of the output to a level that the memory can handle. (Edit: use the aggregate function for this)

**Comment by ALEJANDRA-TOMASINI** [comment]
The protected areas were reduced to a single community cell, the rest was each individual cell outside PA.
I fix the script so now you should be able to run it with the files in the repository. the lines for files that need to be loaded say "LOAD THIS". I tried to do the phylogenetic beta diversity (line 447) not sure that I did it correctly since I got a weird error "CANNOT ALLOCATE VECTOR OF SIZE 500 GB.."
 Also the zscaleLoggave an error  so that didn't work either 
(I just resend you this from a mail i sent before )

**Comment by ALEJANDRA-TOMASINI** [comment]
I could make the cells bigger so the memory can handle it but wouldn't that be even less informative? I would choose a resolution of may be 50km2 and I think the reason for calculating the beta diversity is to get the areas outside PAs that can be priority for conservation so 50km would be way to big and also I've been working everything with 10km2 resolution so changing the resolution of only this would be a bit "messy", wouldn't it?  Also if it manage to calculate the beta diversity with that same data set, it should be able to do it for the phylogenetic beta diversity I think, thats why I'm wondering if maybe I did something wrong with my input matrix that I am not aware of

**Comment by JamesDMSpeed** [comment]
Ok, I tried to run it on the server, with the same issue. 
Since you do not need to calculate all pairwise distances, you could set it up to contrast each non-protected area cell to the protected community, and write that value immediately to a raster. You could do this in a for loop most simply. The other option is to aggregate the cells
